# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture_caption',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='post',
            name='picture_orientation',
            field=models.CharField(choices=[('L', 'L'), ('P', 'P')], default='L', max_length=1),
        ),
    ]
