# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-22 14:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MEETINGS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATE', models.DateField(default='2016-08-22', verbose_name='DATE')),
                ('TIME', models.TimeField(default='14:22', verbose_name='TIME')),
                ('VENUE', models.CharField(default='Committee Room', max_length=100, verbose_name='VENUE')),
                ('SPEAKER', models.CharField(default='TBA', max_length=100, verbose_name='SPEAKER')),
                ('TOPIC', models.TextField(default='TBA', verbose_name='TOPIC')),
            ],
        ),
        migrations.CreateModel(
            name='MUTANTS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('INDEX', models.CharField(default=0, max_length=100, verbose_name='INDEX')),
                ('LOCATION_IDENTIFIER', models.CharField(max_length=100, verbose_name='LOCATION_IDENTIFIER')),
                ('GROUP', models.CharField(max_length=100, verbose_name='GROUP')),
                ('COLLECTION_NUMBER', models.CharField(max_length=100, verbose_name='COLLECTION_NUMBER')),
                ('GENOTYPE', models.TextField(default='no details available', verbose_name='GENOTYPE')),
                ('CONSTRUCTION_DETAILS', models.TextField(default='no details available', verbose_name='CONSTRUCTION_DETAILS')),
                ('DATE', models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='DATE')),
                ('LAB_MEMBER', models.CharField(default='no details available', max_length=100, verbose_name='LAB_MEMBER')),
                ('GROWTH_CONDITIONS', models.TextField(default='no details available', verbose_name='GROWTH_CONDITIONS')),
                ('KNOWN_AS', models.TextField(default='no details available', verbose_name='KNOWN_AS')),
                ('NOTES', models.TextField(default='no notes available', verbose_name='NOTES')),
                ('ADDED_TO_DB', models.DateTimeField(default=django.utils.timezone.now, verbose_name='DATE')),
            ],
        ),
        migrations.CreateModel(
            name='NOTIFICATIONS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOTIFICATION', models.TextField(default='...', verbose_name='NOTIFICATION')),
                ('DATE', models.DateField(default='2016-08-22', verbose_name='DATE')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
