# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='DATE',
            field=models.DateField(default='2016-09-14', verbose_name='DATE'),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='TIME',
            field=models.TimeField(default='13:35', verbose_name='TIME'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='DATE',
            field=models.DateField(default='2016-09-14', verbose_name='DATE'),
        ),
    ]
