# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-14 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databases', '0007_auto_20160914_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='TIME',
            field=models.TimeField(default='14:03', verbose_name='TIME'),
        ),
    ]
